# Numpy Tutorial

based on http://cs231n.github.io/python-numpy-tutorial/

In [3]:
import numpy as np


the next command is used to print all of the outputs to screen (this is not the default mode)

In [27]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Creating arrays

In [11]:
a = np.array([1, 2, 3])   # Create a rank 1 array
a

array([1, 2, 3])

In [12]:
b = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64) # Create a 2-dim array
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
type(a)       # Prints "<class 'numpy.ndarray'>"
a.shape          # Prints "(3,)"
a[0], a[1], a[2]  # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
a                 # Prints "[5, 2, 3]"
a.astype('float') # changes the data type of a

numpy.ndarray

(3,)

(5, 2, 3)

array([5, 2, 3])

array([5., 2., 3.])

In [21]:
print('returns the number of dimensions of b', b.ndim)

print('returns the shape of b', b.shape)
print('returns the data type of b', b.dtype)

print('returns the number of elements of b', b.size)

print("returns information about the array's memory layout")
b.flags

print("returns the length of one array element in bytes", b.itemsize)
     
print("returns the total consumed bytes of the array's elements", b.nbytes)

returns the number of dimensions of b 2
returns the shape of b (2, 4)
returns the data type of b int64
returns the number of elements of b 8
returns information about the array's memory layout


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

returns the length of one array element in bytes 8
returns the total consumed bytes of the array's elements 64


### Other ways to create an array

In [15]:
np.ones((3,4)) # Create an array of ones
np.zeros((2,3,4),dtype=np.int16) # Create an array of zeros
np.random.random((2,2)) # Create an array with random values

np.empty((3,2)) # Create an empty array

np.full((2,2),7) # Create a full array

np.arange(10,25,5) # Create an array of evenly-spaced values (similar to range)

np.linspace(0,2,9) # Create an array of evenly-spaced values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

array([[0.08740357, 0.20670236],
       [0.37041588, 0.09493886]])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

array([[7, 7],
       [7, 7]])

array([10, 15, 20])

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Indexing and slicing

In [ ]:

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

In [ ]:

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [ ]:
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

## Arrays Mathemtics


In [26]:

a = np.arange(4)
a
b
a + b # if in the dimension where a has size 1, and the other array has a size greater than 1 (that is, 3), the first array behaves as if it were copied along that dimension.


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [29]:
## Mutating Arrays

In [ ]:
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [30]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [32]:
x
np.reshape(x, (3, 4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.reshape(x, -1)
np.ravel(x)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

b = np.floor(10*np.random.random((2,2)))
b

np.vstack((a,b)) # horizontal stack

np.hstack((a,b)) # vertical stack


### loading data

In [ ]:
x, y, z = np.loadtxt('data.txt', skiprows=1, unpack=True) # Skip the first row; Return the columns as separate arrays with unpack=TRUE